name: acme
dependencies:
  - fsspec
  - matplotlib
  - nodejs
  - numba
  - numpy
  - pandas
  - pip
  - pyarrow
  - python
  - python-dotenv
  - scikit-learn
  - scipy
  - seaborn
  - setuptools-rust
  - zstandard
  - pip:
    - adlfs
    - bokeh
    - duckdb
    - dask[complete]
    - datamapplot
    - fast-hdbscan
    - gcsfs
    - glasbey
    - hdbscan
    - holoviews
    - ipykernel
    - ipympl
    - ipywidgets
    - jupyterlab
    - jupyterlab-lsp
    - jupyter-server-proxy
    - magic-duckdb
    - panel
    - python-dotenv
    - python-lsp-server
    - requests
    - s3fs
    - thisnotthat
    - tqdm
    - umap-learn[plot]
    - vectorizers
channels:
  - defaults
