name: data-science
dependencies:
  - fsspec
  - graphviz
  - matplotlib
  - nb_conda
  - nb_conda_kernels
  - nodejs
  - numba
  - numpy
  - pandas
  - pip
  - pyarrow
  - pycairo
  - pygraphviz
  - python
  - python-graphviz
  - scikit-learn
  - scipy
  - seaborn
  - setuptools-rust
  - zstandard
  - pip:
    - adlfs
    - bokeh
    - duckdb
    - dask[complete]
    - dask-sql
    - dask-labextension
    - datamapplot
    - fast-hdbscan
    - fastnode2vec
    - hdbscan
    - holoviews
    - hypernetx
    - ipykernel
    - ipympl
    - ipywidgets
    - jupyterlab
    - jupyterlab-lsp
    - jupyter-server-proxy
    - magic-duckdb
    - panel
    - partition-igraph
    - python-dotenv
    - python-igraph
    - python-lsp-server
    - scikit-network
    - thisnotthat
    - umap-learn[plot]
    - git+https://github.com/TutteInstitute/vectorizers
    - xgi
channels:
  - defaults
